[package]
name = "query"
version = "0.1.0"
edition = "2024"

[dependencies]
comrak = { version = "0.50", features = ["syntect"] }
dashmap = { version = "6.1", features = ["serde"] }
dyn-clone = "1.0"
either = "1.15"
generic-array = { version = "0.14", features = ["serde"] }
hex = "0.4"
ignore = "0.4"
minify-html = "0.18"
petgraph = { version = "0.8", features = ["serde-1"] }
relative-path = "2.0"
postcard = { version = "1.1", features = ["use-std"] }
serde = { version = "1.0", features = ["derive"] }
sha2 = "0.10"
tracing = "0.1"
zstd = "0.13"

[dependencies.rquickjs]
version = "0.11"
features = [
  "either",
  "rust-alloc",
  "loader",
  "macro",
  "phf",
]
