[package]
name = "query"
version = "0.1.0"
edition = "2024"

[dependencies]
comrak = { version = "0.50", features = ["syntect"] }
dashmap = "6.1"
dyn-clone = "1.0"
either = "1.15"
ignore = "0.4"
minify-html = "0.18"
petgraph = "0.8"
sha2 = "0.10"

[dependencies.rquickjs]
version = "0.11"
features = [
  "either",
  "rust-alloc",
  "loader",
  "macro",
  "phf",
]
