[package]
name = "driver"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["cargo"] }
query = { path = "../query" }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
